# Generated by Django 4.1.2 on 2022-10-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='down_like_by',
            new_name='disliked_by',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='up_like_by',
            new_name='liked_by',
        ),
    ]
